/**
 * EXPERIMENTAL PROTOTYPE — LANE W1P/W1R: the W2 structural delta, asserted from
 * compiled candidates rather than from their description.
 *
 * TWO builds are measured, and the distinction is the point:
 *   E1 — the probe used by Sd4LaneW12 for OBSERVATION. Its liveness helper is a
 *        public view so tests can read liveness directly. Feasibility only.
 *   E0 — the W2 DESIGN FORECAST adopted by Lane W1R: the same candidate with the
 *        helper internal. This is the delta W2 is expected to ship.
 *
 * Both are in-memory candidates. Neither is the final W2 artifact; they
 * establish candidate feasibility, and the E0 numbers are the forecast.
 */
import { expect } from "chai";
import { ethers } from "./connection.js";
import { buildLaneWColocated, buildLaneWColocatedE0 } from "./sd4-candidate-kernels.js";
import { deployWorld } from "../stateful/world.js";

const sigsOf = (iface: ethers.Interface, type: "function" | "event") =>
  iface.fragments
    .filter((f) => f.type === type)
    .map((f) => (f as ethers.FunctionFragment | ethers.EventFragment).format("sighash"))
    .sort();

async function delta(build: () => { abi: unknown[] }) {
  const w = await deployWorld({ label: `w1p-abi-${Math.random().toString(36).slice(2, 8)}` });
  const base = w.vault.interface;
  const cand = new ethers.Interface(build().abi as ethers.InterfaceAbi);
  const gb = base.getFunction("recovery")!;
  const gc = cand.getFunction("recovery")!;
  return {
    addedFns: sigsOf(cand, "function").filter((s) => !sigsOf(base, "function").includes(s)),
    removedFns: sigsOf(base, "function").filter((s) => !sigsOf(cand, "function").includes(s)),
    addedEvs: sigsOf(cand, "event").filter((s) => !sigsOf(base, "event").includes(s)),
    getterSame: gc.selector === gb.selector && gc.outputs.map((o) => o.type).join() === gb.outputs.map((o) => o.type).join(),
    getterFields: gc.outputs.length,
  };
}

const QCANCEL = "cancelRecoveryByQuorum((address[],bool[],uint256[],bytes[]),uint256,uint64)";

describe("SD-4 lane W1P/W1R — Candidate C structural delta, from the ABI", () => {
  it("E1 probe (observability instrument): +2 selectors, +1 event, recovery() identical", async function () {
    this.timeout(600_000);
    const d = await delta(buildLaneWColocated);
    expect(d.removedFns).to.deep.equal([]);
    expect(d.addedFns).to.deep.equal([QCANCEL, "effectiveLiveRecovery()"]);
    expect(d.addedEvs).to.deep.equal(["RecoveryCancelledByQuorum(uint32)"]);
    expect(d.getterSame, "autogenerated getter byte-identical").to.equal(true);
    expect(d.getterFields).to.equal(8);
  });

  it("E0 forecast (W2 target): +1 selector, +1 event, recovery() identical — liveness is a pure function of public data", async function () {
    this.timeout(600_000);
    const d = await delta(buildLaneWColocatedE0);
    expect(d.removedFns).to.deep.equal([]);
    expect(d.addedFns, "the ONLY new selector is K-9's guardian cancellation").to.deep.equal([QCANCEL]);
    expect(d.addedEvs).to.deep.equal(["RecoveryCancelledByQuorum(uint32)"]);
    expect(d.getterSame).to.equal(true);
    // No new public state variable on either build: one would surface as a getter.
    expect(d.addedFns.filter((s) => !s.includes("(")).length).to.equal(0);
  });
});
