/**
 * Reproducible PQ/ZK proof-artifact manifest (builder + validator).
 *
 * This module produces a deterministic, locally regenerable *manifest* that
 * demonstrates the SHAPE of a future ZK/PQ proof output for an ML-DSA-65
 * withdrawal-authorization fixture. It binds together, with no toolchain:
 *
 *   - the deterministic open-verifier evidence core (a keccak256 of the
 *     `walletwall.pq-verifier.v1` verification result — hashes only),
 *   - the SP1 guest *journal* / public values (ProverClient.encodePublicValues),
 *     which is a pure, deterministic derivation that never proves or executes,
 *   - the verifier build/version, vector-set identifier, and the journal output
 *     hash.
 *
 * What it is NOT:
 *   - It is NOT a real proof. No Groth16 proof bytes are generated. The `proof`
 *     block is reported as `status: "gated"` because heavy SP1 proving stays
 *     behind RUN_SP1_E2E=1 and an external prover (see docs/ZK_Prover_Runbook.md).
 *   - It is NOT on-chain verification, NOT custody, and makes NO "quantum-proof"
 *     guarantee.
 *
 * The manifest carries ONLY hashes plus the journal public values (which are
 * themselves only hashes + chainId + verifier address). It never embeds raw
 * key, signature, or message bytes. `validateProofArtifact` re-derives the
 * journal binding so a tampered or raw-material-bearing artifact is rejected.
 *
 * Research prototype. Not audited. Testnet/local only. Do not use real funds.
 */
import { getBytes, keccak256, toUtf8Bytes, isHexString, dataLength, isAddress, AbiCoder } from "ethers";

import type { PQVerificationResult } from "../../src/verifier/schema";
import { verifyMLDSA65Detailed } from "../../src/verifier/ml-dsa-65";
import { PQ_VERIFIER_NAME } from "../../src/verifier/schema";
import { ProverClient } from "../prover-client";

/** Stable manifest schema identifier. Bump only on a breaking shape change. */
export const PQ_PROOF_ARTIFACT_SCHEMA_VERSION = "walletwall.pq-proof-artifact.v1";

/** The single manifest kind this module emits. */
export const PQ_PROOF_ARTIFACT_KIND = "sp1-mldsa65-journal-manifest";

/** Tooling identifiers (the proof scheme a future real proof would use). */
export const PQ_PROOF_PROVER = "sp1";
export const PQ_PROOF_SCHEME = "groth16";

/** Closed set of proof-presence statuses. */
export const PQ_PROOF_STATUS = {
  /** No proof bytes are present; heavy proving is gated/optional. */
  GATED: "gated",
  /** Real proof bytes were generated by a configured prover (not in CI). */
  GENERATED: "generated",
} as const;
export type PQProofStatus = (typeof PQ_PROOF_STATUS)[keyof typeof PQ_PROOF_STATUS];

/** Default human-readable reason the proof block is gated. */
export const GATED_PROOF_REASON =
  "Heavy SP1 Groth16 proving is gated behind RUN_SP1_E2E=1 and an external prover; not produced in CI. This manifest pins the deterministic journal only.";

export interface PQProofArtifactJournal {
  /** ABI-encoded SP1 public values (the guest journal), 160 bytes. */
  publicValues: string;
  /** keccak256 of `publicValues` — the deterministic output hash. */
  publicValuesHash: string;
  /** Chain id bound into the journal (uint64). */
  chainId: number;
  /** Verifier address bound into the journal. */
  verifierAddress: string;
}

export interface PQProofArtifactProof {
  status: PQProofStatus;
  scheme: typeof PQ_PROOF_SCHEME;
  generated: boolean;
  reason: string;
}

export interface PQProofArtifact {
  schema: typeof PQ_PROOF_ARTIFACT_SCHEMA_VERSION;
  /** ISO-8601 UTC instant; the only non-deterministic field. */
  generatedAt: string;
  artifact: {
    kind: typeof PQ_PROOF_ARTIFACT_KIND;
    /** Vector-set identifier the fixture was drawn from. */
    vectorSet: string;
    /** Verifier build/version (from the deterministic verification result). */
    verifier: { name: string; version: string };
    tooling: { prover: typeof PQ_PROOF_PROVER; scheme: typeof PQ_PROOF_SCHEME };
    /** keccak256 of the canonical deterministic verification result (evidence core). */
    sourceEvidenceHash: string;
    input: { messageHash: string; publicKeyHash: string; signatureHash: string };
    journal: PQProofArtifactJournal;
  };
  proof: PQProofArtifactProof;
  regeneration: {
    /** Command that regenerates this artifact deterministically. */
    command: string;
    deterministic: boolean;
  };
}

export interface BuildProofArtifactInput {
  /** 32-byte withdrawal digest; also the ML-DSA message that was signed. */
  withdrawalDigest: string;
  publicKey: Uint8Array;
  signature: Uint8Array;
  chainId: bigint;
  verifierAddress: string;
  vectorSet: string;
  generatedAt?: string | Date;
  /** Defaults to the gated (no real proof) status. */
  proof?: PQProofArtifactProof;
  /** Command string recorded under `regeneration.command`. */
  command?: string;
}

/** keccak256 over the canonical deterministic verification result (no timestamp). */
export function sourceEvidenceHash(verification: PQVerificationResult): string {
  return keccak256(toUtf8Bytes(JSON.stringify(verification)));
}

/**
 * Build the deterministic proof-artifact manifest.
 *
 * Everything except `generatedAt` is a pure function of the fixture inputs, so
 * regenerating with the same fixture + fixed timestamp yields a byte-identical
 * artifact (pinned by the no-drift test).
 */
export function buildProofArtifact(input: BuildProofArtifactInput): PQProofArtifact {
  const message = getBytes(input.withdrawalDigest);
  const verification = verifyMLDSA65Detailed(input.publicKey, message, input.signature);

  const publicValues = ProverClient.encodePublicValues(
    input.withdrawalDigest,
    input.publicKey,
    input.signature,
    input.chainId,
    input.verifierAddress,
  );

  const generatedAt =
    input.generatedAt instanceof Date
      ? input.generatedAt.toISOString()
      : (input.generatedAt ?? new Date().toISOString());

  const proof: PQProofArtifactProof = input.proof ?? {
    status: PQ_PROOF_STATUS.GATED,
    scheme: PQ_PROOF_SCHEME,
    generated: false,
    reason: GATED_PROOF_REASON,
  };

  return {
    schema: PQ_PROOF_ARTIFACT_SCHEMA_VERSION,
    generatedAt,
    artifact: {
      kind: PQ_PROOF_ARTIFACT_KIND,
      vectorSet: input.vectorSet,
      verifier: { name: verification.verifier.name, version: verification.verifier.version },
      tooling: { prover: PQ_PROOF_PROVER, scheme: PQ_PROOF_SCHEME },
      sourceEvidenceHash: sourceEvidenceHash(verification),
      input: {
        messageHash: verification.input.messageHash,
        publicKeyHash: verification.input.publicKeyHash,
        signatureHash: verification.input.signatureHash,
      },
      journal: {
        publicValues,
        publicValuesHash: keccak256(publicValues),
        chainId: Number(input.chainId),
        verifierAddress: input.verifierAddress,
      },
    },
    proof,
    regeneration: {
      command: input.command ?? "npm run proof:artifact",
      deterministic: true,
    },
  };
}

export interface ProofArtifactValidation {
  valid: boolean;
  errors: string[];
}

const HASH_RE = /^0x[0-9a-f]{64}$/;
const ISO_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/;
const PROOF_STATUSES = new Set<string>(Object.values(PQ_PROOF_STATUS));

/**
 * Closed key sets per object level, mirroring `additionalProperties: false`
 * and the `required` sets in docs/schemas/pq-proof-artifact.v1.schema.json.
 * They let the authoritative validator reject unknown keys at *every* level —
 * not just the top — so raw key/signature/message material cannot be smuggled
 * into an unrecognized nested field (e.g. `artifact.input.rawSignature`).
 */
const ARTIFACT_KEYS = ["kind", "vectorSet", "verifier", "tooling", "sourceEvidenceHash", "input", "journal"];
const VERIFIER_KEYS = ["name", "version"];
const TOOLING_KEYS = ["prover", "scheme"];
const INPUT_KEYS = ["messageHash", "publicKeyHash", "signatureHash"];
const JOURNAL_KEYS = ["publicValues", "publicValuesHash", "chainId", "verifierAddress"];
const PROOF_KEYS = ["status", "scheme", "generated", "reason"];
const REGEN_KEYS = ["command", "deterministic"];

function isHash(v: unknown): v is string {
  return typeof v === "string" && HASH_RE.test(v);
}

/**
 * Push an error for every own key of `obj` not in `allowed`. No-ops for
 * non-objects (those are reported by their own type checks). This enforces the
 * schema's `additionalProperties: false` for nested objects, closing the hole
 * where the top-level-only key check let raw material ride in a nested field.
 */
function rejectUnknownKeys(obj: unknown, allowed: readonly string[], path: string, errors: string[]): void {
  if (typeof obj !== "object" || obj === null) return;
  for (const k of Object.keys(obj)) {
    if (!allowed.includes(k)) errors.push(`unexpected key in ${path}: ${k}`);
  }
}

/**
 * Strictly validate a proof-artifact manifest.
 *
 * Rejects unknown keys at every object level (mirroring the JSON Schema's
 * `additionalProperties: false`, so raw material cannot hide in an
 * unrecognized nested field), malformed hashes/timestamps, an inconsistent
 * proof.status/generated pairing, a journal that does not decode to the
 * declared input hashes, and any embedded raw key/signature material. The
 * journal is the only intentionally long hex field; it is validated to be
 * exactly 160 bytes AND to decode to the same hashes carried in `input`, which
 * proves it holds hashes only.
 */
export function validateProofArtifact(value: unknown): ProofArtifactValidation {
  const errors: string[] = [];
  if (typeof value !== "object" || value === null) {
    return { valid: false, errors: ["artifact must be an object"] };
  }
  const e = value as Record<string, unknown>;

  const allowedTop = new Set(["schema", "generatedAt", "artifact", "proof", "regeneration"]);
  for (const k of Object.keys(e)) {
    if (!allowedTop.has(k)) errors.push(`unexpected top-level key: ${k}`);
  }

  if (e.schema !== PQ_PROOF_ARTIFACT_SCHEMA_VERSION) errors.push(`schema must be ${PQ_PROOF_ARTIFACT_SCHEMA_VERSION}`);
  if (typeof e.generatedAt !== "string" || !ISO_RE.test(e.generatedAt) || Number.isNaN(Date.parse(e.generatedAt))) {
    errors.push("generatedAt must be an ISO-8601 UTC timestamp");
  }

  const a = e.artifact as Record<string, unknown> | undefined;
  if (!a || typeof a !== "object") {
    errors.push("artifact must be an object");
  } else {
    rejectUnknownKeys(a, ARTIFACT_KEYS, "artifact", errors);
    if (a.kind !== PQ_PROOF_ARTIFACT_KIND) errors.push(`artifact.kind must be ${PQ_PROOF_ARTIFACT_KIND}`);
    if (typeof a.vectorSet !== "string" || a.vectorSet.length === 0) {
      errors.push("artifact.vectorSet must be a non-empty string");
    }
    const verifier = a.verifier as Record<string, unknown> | undefined;
    if (!verifier || verifier.name !== PQ_VERIFIER_NAME || typeof verifier.version !== "string") {
      errors.push(`artifact.verifier must be { name: ${PQ_VERIFIER_NAME}, version: string }`);
    }
    rejectUnknownKeys(verifier, VERIFIER_KEYS, "artifact.verifier", errors);
    const tooling = a.tooling as Record<string, unknown> | undefined;
    if (!tooling || tooling.prover !== PQ_PROOF_PROVER || tooling.scheme !== PQ_PROOF_SCHEME) {
      errors.push(`artifact.tooling must be { prover: ${PQ_PROOF_PROVER}, scheme: ${PQ_PROOF_SCHEME} }`);
    }
    rejectUnknownKeys(tooling, TOOLING_KEYS, "artifact.tooling", errors);
    if (!isHash(a.sourceEvidenceHash)) errors.push("artifact.sourceEvidenceHash must be a 0x keccak256 hash");

    const input = a.input as Record<string, unknown> | undefined;
    if (!input) {
      errors.push("artifact.input is required");
    } else {
      for (const k of ["messageHash", "publicKeyHash", "signatureHash"] as const) {
        if (!isHash(input[k])) errors.push(`artifact.input.${k} must be a 0x keccak256 hash`);
      }
      rejectUnknownKeys(input, INPUT_KEYS, "artifact.input", errors);
    }

    const journal = a.journal as Record<string, unknown> | undefined;
    if (!journal) {
      errors.push("artifact.journal is required");
    } else {
      rejectUnknownKeys(journal, JOURNAL_KEYS, "artifact.journal", errors);
      validateJournal(journal, input, errors);
    }
  }

  const proof = e.proof as Record<string, unknown> | undefined;
  if (!proof) {
    errors.push("proof is required");
  } else {
    rejectUnknownKeys(proof, PROOF_KEYS, "proof", errors);
    if (typeof proof.status !== "string" || !PROOF_STATUSES.has(proof.status)) {
      errors.push(`proof.status must be one of ${[...PROOF_STATUSES].join(", ")}`);
    }
    if (proof.scheme !== PQ_PROOF_SCHEME) errors.push(`proof.scheme must be ${PQ_PROOF_SCHEME}`);
    if (typeof proof.generated !== "boolean") errors.push("proof.generated must be a boolean");
    if (typeof proof.reason !== "string" || proof.reason.length === 0) {
      errors.push("proof.reason must be a non-empty string");
    }
    // generated is true iff status is "generated".
    if (typeof proof.generated === "boolean" && typeof proof.status === "string") {
      const shouldBeGenerated = proof.status === PQ_PROOF_STATUS.GENERATED;
      if (proof.generated !== shouldBeGenerated) {
        errors.push('proof.generated must be true iff proof.status is "generated"');
      }
    }
  }

  const regen = e.regeneration as Record<string, unknown> | undefined;
  if (!regen) {
    errors.push("regeneration is required");
  } else {
    rejectUnknownKeys(regen, REGEN_KEYS, "regeneration", errors);
    if (typeof regen.command !== "string" || regen.command.length === 0) {
      errors.push("regeneration.command must be a non-empty string");
    }
    if (typeof regen.deterministic !== "boolean") errors.push("regeneration.deterministic must be a boolean");
  }

  return { valid: errors.length === 0, errors };
}

/** Validate the journal shape and prove it binds to the declared input hashes. */
function validateJournal(
  journal: Record<string, unknown>,
  input: Record<string, unknown> | undefined,
  errors: string[],
): void {
  const pv = journal.publicValues;
  if (typeof pv !== "string" || !isHexString(pv) || dataLength(pv) !== 160) {
    errors.push("artifact.journal.publicValues must be 160-byte hex");
    return;
  }
  if (!isHash(journal.publicValuesHash) || journal.publicValuesHash !== keccak256(pv)) {
    errors.push("artifact.journal.publicValuesHash must be keccak256(publicValues)");
  }
  if (typeof journal.chainId !== "number" || !Number.isInteger(journal.chainId) || journal.chainId < 0) {
    errors.push("artifact.journal.chainId must be a non-negative integer");
  }
  if (typeof journal.verifierAddress !== "string" || !isAddress(journal.verifierAddress)) {
    errors.push("artifact.journal.verifierAddress must be a valid EVM address");
  }

  // Decode the journal and cross-check it against the declared inputs. This is
  // the defense that proves the publicValues blob carries only hashes (no raw
  // key/signature) and is internally consistent.
  //
  // The ABI encoding is (withdrawalDigest, pkHash, sigHash, uint64, address).
  // All three hash fields are cross-checked so a partially-tampered artifact
  // (e.g. flipping only messageHash in artifact.input) is caught here.
  try {
    const [msgHash, pkHash, sigHash, chainId, verifierAddress] = new AbiCoder().decode(
      ["bytes32", "bytes32", "bytes32", "uint64", "address"],
      pv,
    );
    // The journal carries the raw withdrawalDigest (bytes32); artifact.input.messageHash
    // is keccak256 of those same bytes. Cross-check the round-trip so a tampered
    // messageHash field is caught even when the journal itself is untouched.
    if (input && isHash(input.messageHash) && keccak256(msgHash) !== (input.messageHash as string)) {
      errors.push("journal messageHash does not match artifact.input.messageHash");
    }
    if (input && isHash(input.publicKeyHash) && pkHash.toLowerCase() !== (input.publicKeyHash as string)) {
      errors.push("journal publicKeyHash does not match artifact.input.publicKeyHash");
    }
    if (input && isHash(input.signatureHash) && sigHash.toLowerCase() !== (input.signatureHash as string)) {
      errors.push("journal signatureHash does not match artifact.input.signatureHash");
    }
    if (typeof journal.chainId === "number" && Number(chainId) !== journal.chainId) {
      errors.push("journal chainId does not match artifact.journal.chainId");
    }
    if (
      typeof journal.verifierAddress === "string" &&
      verifierAddress.toLowerCase() !== journal.verifierAddress.toLowerCase()
    ) {
      errors.push("journal verifierAddress does not match artifact.journal.verifierAddress");
    }
  } catch {
    errors.push("artifact.journal.publicValues failed to decode as (bytes32,bytes32,bytes32,uint64,address)");
  }
}

/** Type-guard form of {@link validateProofArtifact}. */
export function isPQProofArtifact(value: unknown): value is PQProofArtifact {
  return validateProofArtifact(value).valid;
}
