import { ethers } from "ethers";

/**
 * @title Prover Client
 * @notice Production-grade TS wrapper for generating ZK proofs for ML-DSA-65.
 */
export class ProverClient {
  /**
   * Encodes an SP1 proof generated by a real, independently configured prover.
   *
   * @param withdrawalDigest 32-byte digest of the withdrawal request.
   * @param publicKey The raw ML-DSA-65 public key.
   * @param signature The raw ML-DSA-65 signature.
   * @param chainId The chain ID where the proof will be verified.
   * @param verifierAddress The address of the ZKMLDSAVerifier contract.
   * @param proofBytes Proof bytes returned by the SP1 prover.
   * @returns A hex-encoded proof payload for Solidity.
   */
  static encodeProof(
    withdrawalDigest: string,
    publicKey: Uint8Array,
    signature: Uint8Array,
    chainId: bigint,
    verifierAddress: string,
    proofBytes: string,
  ): Promise<string> {
    if (!ethers.isHexString(withdrawalDigest, 32)) {
      throw new Error("withdrawalDigest must be a bytes32 hex value");
    }
    if (!ethers.isAddress(verifierAddress)) {
      throw new Error("verifierAddress must be a valid EVM address");
    }
    if (publicKey.length !== 1952) {
      throw new Error("ML-DSA-65 public keys must be 1952 bytes");
    }
    if (signature.length !== 3309) {
      throw new Error("ML-DSA-65 signatures must be 3309 bytes");
    }
    if (chainId < 0n || chainId > 0xffffffffffffffffn) {
      throw new Error("chainId must fit in uint64");
    }
    if (!ethers.isHexString(proofBytes) || ethers.dataLength(proofBytes) === 0) {
      throw new Error("proofBytes must be non-empty hex returned by an SP1 prover");
    }

    const pkHash = ethers.keccak256(publicKey);
    const sigHash = ethers.keccak256(signature);

    const abiCoder = new ethers.AbiCoder();

    // The journal must match exactly what the guest program commits.
    // In our guest, we commit 5 words of 32 bytes each.
    const publicValues = abiCoder.encode(
      ["bytes32", "bytes32", "bytes32", "uint64", "address"],
      [withdrawalDigest, pkHash, sigHash, chainId, verifierAddress],
    );

    // The Solidity verifier expects: abi.encode(publicValues, proofBytes)
    const payload = abiCoder.encode(["bytes", "bytes"], [publicValues, proofBytes]);

    return payload;
  }
}
