import { ethers } from "ethers";
import { spawnSync } from "node:child_process";
import { mkdtempSync, writeFileSync, rmSync, existsSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { isAbsolute, join, resolve } from "node:path";

/** JSON emitted by `mldsa65-host prove`. */
interface HostProveOutput {
  vkey: string;
  publicValues: string;
  proofBytes: string;
}

/**
 * @title Prover Client
 * @notice Production-grade TS wrapper for generating ZK proofs for ML-DSA-65.
 */
export class ProverClient {
  /**
   * Generates a real SP1 proof by shelling out to the `mldsa65-host` binary
   * (zkvm/host) and encodes it for {ZKMLDSAVerifier}.
   *
   * This requires the SP1 toolchain and a configured prover (local or the
   * Succinct Prover Network); it is NOT exercised by CI, which uses the mock
   * verifier path. See docs/ZK_Prover_Runbook.md. The host binary path defaults
   * to `zkvm/host/target/release/mldsa65-host` and can be overridden with
   * `SP1_HOST_BIN`.
   *
   * @param withdrawalDigest 32-byte digest of the withdrawal request.
   * @param publicKey The raw ML-DSA-65 public key.
   * @param signature The raw ML-DSA-65 signature.
   * @param chainId The chain ID where the proof will be verified.
   * @param verifierAddress The address of the ZKMLDSAVerifier contract.
   * @param expectedVkey Optional bytes32 program vKey to assert against the
   *        guest the host actually proved (defends against an unpinned guest).
   * @returns A hex-encoded proof payload for Solidity.
   */
  static async generateProof(
    withdrawalDigest: string,
    publicKey: Uint8Array,
    signature: Uint8Array,
    chainId: bigint,
    verifierAddress: string,
    expectedVkey?: string,
  ): Promise<string> {
    const hostBin = ProverClient.resolveHostBin();

    const dir = mkdtempSync(join(tmpdir(), "mldsa65-"));
    const inputsPath = join(dir, "inputs.json");
    try {
      writeFileSync(
        inputsPath,
        JSON.stringify({
          withdrawalDigest,
          publicKey: ethers.hexlify(publicKey),
          signature: ethers.hexlify(signature),
          chainId: Number(chainId),
          verifierAddress,
        }),
      );

      const result = spawnSync(hostBin, ["prove", inputsPath], { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
      if (result.error) {
        throw new Error(`failed to launch SP1 host (${hostBin}): ${result.error.message}`);
      }
      if (result.status !== 0) {
        throw new Error(`SP1 host exited with code ${result.status}: ${result.stderr?.trim() ?? ""}`);
      }

      const output = JSON.parse(result.stdout) as HostProveOutput;
      if (expectedVkey && output.vkey.toLowerCase() !== expectedVkey.toLowerCase()) {
        throw new Error(`prover vKey ${output.vkey} does not match expected ${expectedVkey}`);
      }

      // Re-encode through encodeProof so the public-value derivation and input
      // validation are identical to the mock path and bound to these inputs.
      return ProverClient.encodeProof(
        withdrawalDigest,
        publicKey,
        signature,
        chainId,
        verifierAddress,
        output.proofBytes,
      );
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  }

  /**
   * Encodes an SP1 proof generated by a real, independently configured prover.
   *
   * @param withdrawalDigest 32-byte digest of the withdrawal request.
   * @param publicKey The raw ML-DSA-65 public key.
   * @param signature The raw ML-DSA-65 signature.
   * @param chainId The chain ID where the proof will be verified.
   * @param verifierAddress The address of the ZKMLDSAVerifier contract.
   * @param proofBytes Proof bytes returned by the SP1 prover.
   * @returns A hex-encoded proof payload for Solidity.
   */
  static encodeProof(
    withdrawalDigest: string,
    publicKey: Uint8Array,
    signature: Uint8Array,
    chainId: bigint,
    verifierAddress: string,
    proofBytes: string,
  ): Promise<string> {
    if (!ethers.isHexString(withdrawalDigest, 32)) {
      throw new Error("withdrawalDigest must be a bytes32 hex value");
    }
    if (!ethers.isAddress(verifierAddress)) {
      throw new Error("verifierAddress must be a valid EVM address");
    }
    if (publicKey.length !== 1952) {
      throw new Error("ML-DSA-65 public keys must be 1952 bytes");
    }
    if (signature.length !== 3309) {
      throw new Error("ML-DSA-65 signatures must be 3309 bytes");
    }
    if (chainId < 0n || chainId > 0xffffffffffffffffn) {
      throw new Error("chainId must fit in uint64");
    }
    if (!ethers.isHexString(proofBytes) || ethers.dataLength(proofBytes) === 0) {
      throw new Error("proofBytes must be non-empty hex returned by an SP1 prover");
    }

    const pkHash = ethers.keccak256(publicKey);
    const sigHash = ethers.keccak256(signature);

    const abiCoder = new ethers.AbiCoder();

    // The journal must match exactly what the guest program commits.
    // In our guest, we commit 5 words of 32 bytes each.
    const publicValues = abiCoder.encode(
      ["bytes32", "bytes32", "bytes32", "uint64", "address"],
      [withdrawalDigest, pkHash, sigHash, chainId, verifierAddress],
    );

    // The Solidity verifier expects: abi.encode(publicValues, proofBytes)
    const payload = abiCoder.encode(["bytes", "bytes"], [publicValues, proofBytes]);

    return payload;
  }

  /**
   * Resolves the SP1 host binary to a validated absolute path before it is ever
   * passed to a process launcher. The path is developer-configured (env or the
   * built default), never request data; resolving and requiring an existing
   * regular file keeps the launch off PATH and rejects anything that is not a
   * real binary on disk.
   */
  private static resolveHostBin(): string {
    const configured = process.env.SP1_HOST_BIN ?? join("zkvm", "host", "target", "release", "mldsa65-host");
    const absolute = isAbsolute(configured) ? configured : resolve(configured);
    if (!existsSync(absolute) || !statSync(absolute).isFile()) {
      throw new Error(`SP1 host binary not found at ${absolute}; build zkvm/host or set SP1_HOST_BIN to its path`);
    }
    return absolute;
  }
}
